Calculator:
  hotkey: ^#c
  path: <A_WINDIR>\System32\calc.exe
  titleMatcher: Calculator
  doublePressCloseHotkey: ~ESC # ~ --> First ESC should still clear the calc input
  menu: Programs


Notepad:
  titleMatcher: ahk_exe notepad.exe
  doublePressCloseHotkey: ESC


Paint.NET:
  hotkey: ^#d
  titleMatcher: ahk_exe PaintDotNet.exe
  path: <A_PROGRAMFILES>\paint.net\PaintDotNet.exe
  menu: Programs
  passExplorerPathAsArgument: file
  openWithPathArgs: <exe> "<selectedFiles>"
  openForFiles: png|jpg|jpeg|gif|bmp|tif|tiff|jif|jfif|exif|svg|pdf


Robo 3T (ex Robomongo):
  hotkey: CapsLock & Q
  titleMatcher: ahk_exe robo3t.exe
  path: <A_PROGRAMFILES>\Robo 3T /[0-9]+(.[0-9]+)*/\robo3t.exe
  menu: Programs


HeidiSql:
  hotkey: CapsLock & S
  titleMatcher: ahk_exe heidisql.exe
  path: <A_PROGRAMFILES>\HeidiSQL\heidisql.exe
  menu: Programs


DBeaver:
  path: <USERPROFILE>\AppData\Local\DBeaver\dbeaver.exe
  pathParams: -nl en
  menu: Programs
  active: 0


FileZilla:
  hotkey: ^#f
  titleMatcher: ahk_exe filezilla.exe
  path: <A_PROGRAMFILES>\FileZilla FTP Client\filezilla.exe
  menu: Programs


7-Zip:
  titleMatcher: ahk_exe 7zFM.exe
  path: <A_PROGRAMFILES>\7-zip\7zFM.exe
  menu: Programs


VLC:
  path: <A_PROGRAMFILES>\VideoLAN\VLC\vlc.exe
  menu: Programs


Beyond Compare:
  path: <A_PROGRAMFILES>\Beyond Compare /[0-9]+/\BCompare.exe
  mergePathArgs: " \"<left>" "<right>\""
  menu: Programs


DiffMerge:
  path: <A_PROGRAMFILES>\SourceGear\Common\DiffMerge\sgdm.exe
  mergePathArgs: "-nosplash \"<left>" "<right>\""
  menu: Programs


IrfanView:
  path: <A_PROGRAMFILES>\IrfanView\i_view64.exe
  menu: Programs


TeamViewer:
  path: <A_PROGRAMFILES>\TeamViewer\TeamViewer.exe
  menu: Programs


dotPeek:
  path: <USERPROFILE>\AppData\Local\JetBrains\Installations\dotPeek/[0-9]+/\dotPeek64.exe
  menu: Programs


Ditto:
  path: <A_PROGRAMFILES>\Ditto\Ditto.exe
  menu: Programs
