# Ctrl+Win+S: Sublime Text
Sublime Text:
	hotkey: ^#s
	titleMatcher: ahk_class PX_WINDOW_CLASS
	path: <A_PROGRAMFILES>\Sublime Text 3\sublime_text.exe
	passExplorerPathAsArgument: dir
	openWithPathArgs: <exe> --new-window "<path>"
	menu: Editors


# Win+C: Notepad++. C=Code? :) (N is already mapped to OneNote)
Notepad++:
	hotkey: "#c"
	titleMatcher: ahk_class Notepad++
	path: <A_PROGRAMFILES>\Notepad++\Notepad++.exe
	passExplorerPathAsArgument: file
	explorerFilesSeparator: \"
	menu: Editors


Notepad++ (New Window):
	hotkey: ^#!c
	path: <A_PROGRAMFILES>\Notepad++\Notepad++.exe
	pathParams: -multiInst
	menu: Editors


PowerShell ISE:
	hotkey: !#r
	titleMatcher: ahk_exe powershell_ise.exe
	path: <A_WINDIR>\System32\WindowsPowerShell\v1.0\powershell_ise.exe
	openWithPathArgs: cmd.exe /s /c start /D "<path>" <exe> -file "<selectedFiles>"
	# Other ISE CLI arg: -NoProfile
	passExplorerPathAsArgument: file
	explorerFilesSeparator: ,
	menu: Editors


# https://code.visualstudio.com/docs/editor/command-line
Visual Studio Code:
	hotkey: ^#x
	titleMatcher: ahk_exe Code.exe
	path:
		- <A_PROGRAMFILES>\Microsoft VS Code\Code.exe
		- <A_LOCALAPPDATA>\Programs\Microsoft VS Code\Code.exe
	mergePathArgs: " --diff \"<left>" "<right>\""
	menu: Editors
	openWithPathArgs: <exe> "<selectedFiles>"
	passExplorerPathAsArgument: file


Visual Studio Code (New Window):
	hotkey: ^#!x
	path:
		- <A_PROGRAMFILES>\Microsoft VS Code\Code.exe
		- <A_LOCALAPPDATA>\Programs\Microsoft VS Code\Code.exe
	pathParams: "--new-window"
	menu: Editors


LINQPad:
	path: <A_PROGRAMFILES>\LINQPad/[0-9]/\LINQPad.exe/$/
	menu: Editors


MarkdownPad:
	path: <A_PROGRAMFILES>\MarkdownPad 2\MarkdownPad2.exe
	menu: Editors


Visual Studio 2017:
	path: <A_PROGRAMFILES>\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe
	mergePathArgs: " /diff \"<left>" "<right>\""
	menu: Editors


Visual Studio 2019:
	path: <A_PROGRAMFILES>\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe
	mergePathArgs: " /diff \"<left>" "<right>\""
	menu: Editors
