:::spock-hand::🖖
:::sign_of_the_horns::🤘
:::left-facing_fist::🤛
:::right-facing_fist::🤜
:::reversed_hand_with_middle_finger_extend::🖕

:::double_vertical_bar::⏸
:::black_square_for_stop::⏹
:::black_circle_for_record::⏺

:::skin-tone-2::🏻
:::skin-tone-3::🏼
:::skin-tone-4::🏽
:::skin-tone-5::🏾
:::skin-tone-6::🏿

:::om_symbol::🕉
:::dove_of_peace::🕊
:::kaaba::🕋
:::mosque::🕌
:::synagogue::🕍
:::menorah_with_nine_branches::🕎


:::weight_lifter::🏋
:::golfer::🏌
:::racing_motorcycle::🏍
:::racing_car::🏎
:::cricket_bat_and_ball::🏏
:::volleyball::🏐
:::field_hockey_stick_and_ball::🏑
:::ice_hockey_stick_and_puck::🏒
:::table_tennis_paddle_and_ball::🏓
:::snow_capped_mountain::🏔
:::camping::🏕
:::beach_with_umbrella::🏖
:::building_construction::🏗
:::house_buildings::🏘
:::cityscape::🏙
:::derelict_house_building::🏚
:::classical_building::🏛
:::desert::🏜
:::desert_island::🏝
:::national_park::🏞
:::stadium::🏟


:::waving_white_flag::🏳
:::waving_black_flag::🏴
:::rosette::🏵
:::label::🏷
:::badminton_racquet_and_shuttlecock::🏸
:::bow_and_arrow::🏹
:::amphora::🏺
:::skin_tone_2::🏻
:::skin_tone_3::🏼
:::skin_tone_4::🏽
:::skin_tone_5::🏾
:::skin_tone_6::🏿


:::couch_and_lamp::🛋
:::sleeping_accommodation::🛌
:::shopping_bags::🛍
:::bellhop_bell::🛎
:::bed::🛏
:::place_of_worship::🛐
:::octagonal_sign::🛑
:::shopping_trolley::🛒
:::hammer_and_wrench::🛠
:::shield::🛡
:::oil_drum::🛢
:::motorway::🛣
:::railway_track::🛤
:::motor_boat::🛥
:::small_airplane::🛩
:::airplane_departure::🛫
:::airplane_arriving::🛬
:::satellite::🛰
:::passenger_ship::🛳
:::scooter::🛴
:::motor_scooter::🛵
:::canoe::🛶
:::zipper_mouth_face::🤐
:::money_mouth_face::🤑
:::face_with_thermometer::🤒
:::nerd_face::🤓
:::thinking_face::🤔
:::face_with_head_bandage::🤕
:::robot_face::🤖
:::hugging_face::🤗
:::the_horns::🤘
:::call_me_hand::🤙
:::raised_back_of_hand::🤚
:::left_facing_fist::🤛
:::right_facing_fist::🤜
:::handshake::🤝
:::hand_with_index_and_middle_fingers_cros::🤞
:::face_with_cowboy_hat::🤠
:::clown_face::🤡
:::nauseated_face::🤢
:::rolling_on_the_floor_laughing::🤣
:::drooling_face::🤤
:::lying_face::🤥
:::face_palm::🤦
:::sneezing_face::🤧
:::pregnant_woman::🤰
:::selfie::🤳
:::prince::🤴
:::man_in_tuxedo::🤵
:::mother_christmas::🤶
:::shrug::🤷
:::person_doing_cartwheel::🤸
:::juggling::🤹
:::fencer::🤺
:::wrestlers::🤼
:::water_polo::🤽
:::handball::🤾
:::wilted_flower::🥀
:::drum_with_drumsticks::🥁
:::clinking_glasses::🥂
:::tumbler_glass::🥃
:::spoon::🥄
:::goal_net::🥅
:::first_place_medal::🥇
:::second_place_medal::🥈
:::third_place_medal::🥉
:::boxing_glove::🥊
:::martial_arts_uniform::🥋
:::croissant::🥐
:::avocado::🥑
:::cucumber::🥒
:::bacon::🥓
:::potato::🥔
:::carrot::🥕
:::baguette_bread::🥖
:::green_salad::🥗
:::shallow_pan_of_food::🥘
:::stuffed_flatbread::🥙
:::egg::🥚
:::glass_of_milk::🥛
:::peanuts::🥜
:::kiwifruit::🥝
:::pancakes::🥞
:::crab::🦀
:::lion_face::🦁
:::scorpion::🦂
:::turkey::🦃
:::unicorn_face::🦄
:::eagle::🦅
:::duck::🦆
:::bat::🦇
:::shark::🦈
:::owl::🦉
:::fox_face::🦊
:::butterfly::🦋
:::deer::🦌
:::gorilla::🦍
:::lizard::🦎
:::rhinoceros::🦏
:::shrimp::🦐
:::squid::🦑
:::cheese_wedge::🧀

:::candle::🕯
:::mantelpiece_clock::🕰
:::hole::🕳
:::man_in_business_suit_levitating::🕴
:::sleuth_or_spy::🕵
:::dark_sunglasses::🕶
:::spider::🕷
:::spider_web::🕸
:::joystick::🕹
:::man_dancing::🕺
:::linked_paperclips::🖇
:::lower_left_ballpoint_pen::🖊
:::lower_left_fountain_pen::🖋
:::lower_left_paintbrush::🖌
:::lower_left_crayon::🖍
:::raised_hand_with_fingers_splayed::🖐
:::middle_finger::🖕
:::spock_hand::🖖
:::black_heart::🖤
:::desktop_computer::🖥
:::printer::🖨
:::three_button_mouse::🖱
:::trackball::🖲
:::frame_with_picture::🖼
:::card_index_dividers::🗂
:::card_file_box::🗃
:::file_cabinet::🗄
:::wastebasket::🗑
:::spiral_note_pad::🗒
:::spiral_calendar_pad::🗓
:::compression::🗜
:::old_key::🗝
:::rolled_up_newspaper::🗞
:::dagger_knife::🗡
:::speaking_head_in_silhouette::🗣
:::left_speech_bubble::🗨
:::right_anger_bubble::🗯
:::ballot_box_with_ballot::🗳
