; Hand Gestures
:::fist::{Sleep 250}✊
:::hand::{Sleep 250}✋
:::v::{Sleep 250}✌
:::writing_hand::{Sleep 250}✍
:::raised_hand::{Sleep 250}✋
:::point_up::{Sleep 250}☝
:::point_up_2::{Sleep 250}👆
:::point_down::{Sleep 250}👇
:::point_left::{Sleep 250}👈
:::point_right::{Sleep 250}👉
:::facepunch::{Sleep 250}👊
:::wave::{Sleep 250}👋
:::ok_hand::{Sleep 250}👌
:::+1::👍
:::-1::{Sleep 250}👎
:::clap::{Sleep 250}👏
:::open_hands::{Sleep 250}👐
:::punch::{Sleep 250}👊
:::thumbsup::{Sleep 250}👍
:::thumbsdown::{Sleep 250}👎


:::tongue_face::{Sleep 250}😛
:::white_frowning_face::{Sleep 250}☹
:::relaxed::{Sleep 250}☺

:::satisfied::{Sleep 250}😆
:::grinning::{Sleep 250}😀
:::grin::{Sleep 250}😁
:::joy::{Sleep 250}😂
:::smiley::{Sleep 250}😃
:::smile::{Sleep 250}😄
:::sweat_smile::{Sleep 250}😅
:::laughing::{Sleep 250}😆
:::innocent::{Sleep 250}😇
:::smiling_imp::{Sleep 250}😈
:::wink::{Sleep 250}😉
:::blush::{Sleep 250}😊
:::yum::{Sleep 250}😋
:::relieved::{Sleep 250}😌
:::heart_eyes::{Sleep 250}😍
:::sunglasses::{Sleep 250}😎
:::smirk::{Sleep 250}😏
:::neutral_face::{Sleep 250}😐
:::expressionless::{Sleep 250}😑
:::unamused::{Sleep 250}😒
:::sweat::{Sleep 250}😓
:::pensive::{Sleep 250}😔
:::confused::{Sleep 250}😕
:::confounded::{Sleep 250}😖
:::kissing::{Sleep 250}😗
:::kissing_heart::{Sleep 250}😘
:::kissing_smiling_eyes::{Sleep 250}😙
:::kissing_closed_eyes::{Sleep 250}😚
:::stuck_out_tongue::{Sleep 250}😛
:::stuck_out_tongue_winking_eye::{Sleep 250}😜
:::stuck_out_tongue_closed_eyes::{Sleep 250}😝
:::disappointed::{Sleep 250}😞
:::worried::{Sleep 250}😟
:::angry::{Sleep 250}😠
:::rage::{Sleep 250}😡
:::cry::{Sleep 250}😢
:::persevere::{Sleep 250}😣
:::triumph::{Sleep 250}😤
:::disappointed_relieved::{Sleep 250}😥
:::frowning::{Sleep 250}😦
:::anguished::{Sleep 250}😧
:::fearful::{Sleep 250}😨
:::weary::{Sleep 250}😩
:::sleepy::{Sleep 250}😪
:::tired_face::{Sleep 250}😫
:::grimacing::{Sleep 250}😬
:::sob::{Sleep 250}😭
:::open_mouth::{Sleep 250}😮
:::hushed::{Sleep 250}😯
:::cold_sweat::{Sleep 250}😰
:::scream::{Sleep 250}😱
:::astonished::{Sleep 250}😲
:::flushed::{Sleep 250}😳
:::sleeping::{Sleep 250}😴
:::dizzy_face::{Sleep 250}😵
:::no_mouth::{Sleep 250}😶
:::mask::{Sleep 250}😷
:::smile_cat::{Sleep 250}😸
:::joy_cat::{Sleep 250}😹
:::smiley_cat::{Sleep 250}😺
:::heart_eyes_cat::{Sleep 250}😻
:::smirk_cat::{Sleep 250}😼
:::kissing_cat::{Sleep 250}😽
:::pouting_cat::{Sleep 250}😾
:::crying_cat_face::{Sleep 250}😿
:::scream_cat::{Sleep 250}🙀
:::slightly_frowning_face::{Sleep 250}🙁
:::slightly_smiling_face::{Sleep 250}🙂
:::upside_down_face::{Sleep 250}🙃
:::face_with_rolling_eyes::{Sleep 250}🙄
:::no_good::{Sleep 250}🙅
:::ok_woman::{Sleep 250}🙆
:::bow::{Sleep 250}🙇

:::raising_hand::{Sleep 250}🙋
:::raised_hands::{Sleep 250}🙌
:::person_frowning::{Sleep 250}🙍
:::person_with_pouting_face::{Sleep 250}🙎
:::pray::{Sleep 250}🙏


:::male-farmer::{Sleep 250}👨‍🌾
:::male-cook::{Sleep 250}👨‍🍳
:::male-student::{Sleep 250}👨‍🎓
:::male-singer::{Sleep 250}👨‍🎤
:::male-artist::{Sleep 250}👨‍🎨
:::male-teacher::{Sleep 250}👨‍🏫
:::male-factory-worker::{Sleep 250}👨‍🏭
:::man-boy::{Sleep 250}👨‍👦
:::man-girl::{Sleep 250}👨‍👧
:::male-technologist::{Sleep 250}👨‍💻
:::male-office-worker::{Sleep 250}👨‍💼
:::male-mechanic::{Sleep 250}👨‍🔧
:::male-scientist::{Sleep 250}👨‍🔬
:::male-astronaut::{Sleep 250}👨‍🚀
:::male-firefighter::{Sleep 250}👨‍🚒
:::female-farmer::{Sleep 250}👩‍🌾
:::female-cook::{Sleep 250}👩‍🍳
:::female-student::{Sleep 250}👩‍🎓
:::female-singer::{Sleep 250}👩‍🎤
:::female-artist::{Sleep 250}👩‍🎨
:::female-teacher::{Sleep 250}👩‍🏫
:::female-factory-worker::{Sleep 250}👩‍🏭
:::woman-boy::{Sleep 250}👩‍👦
:::woman-girl::{Sleep 250}👩‍👧
:::female-technologist::{Sleep 250}👩‍💻
:::female-office-worker::{Sleep 250}👩‍💼
:::female-mechanic::{Sleep 250}👩‍🔧
:::female-scientist::{Sleep 250}👩‍🔬
:::female-astronaut::{Sleep 250}👩‍🚀
:::female-firefighter::{Sleep 250}👩‍🚒
:::woman-running::{Sleep 250}🏃‍♀️
:::man-running::{Sleep 250}🏃‍♂️
:::woman-surfing::{Sleep 250}🏄‍♀️
:::man-surfing::{Sleep 250}🏄‍♂️
:::woman-swimming::{Sleep 250}🏊‍♀️
:::man-swimming::{Sleep 250}🏊‍♂️
:::woman-lifting-weights::{Sleep 250}🏋️‍♀️
:::man-lifting-weights::{Sleep 250}🏋️‍♂️
:::woman-golfing::{Sleep 250}🏌️‍♀️
:::man-golfing::{Sleep 250}🏌️‍♂️
:::rainbow-flag::{Sleep 250}🏳️‍🌈
:::eye-in-speech-bubble::{Sleep 250}👁️‍🗨️
:::man-boy-boy::{Sleep 250}👨‍👦‍👦
:::man-girl-boy::{Sleep 250}👨‍👧‍👦
:::man-girl-girl::{Sleep 250}👨‍👧‍👧
:::man-man-boy::{Sleep 250}👨‍👨‍👦
:::man-man-boy-boy::{Sleep 250}👨‍👨‍👦‍👦
:::man-man-girl::{Sleep 250}👨‍👨‍👧
:::man-man-girl-boy::{Sleep 250}👨‍👨‍👧‍👦
:::man-man-girl-girl::{Sleep 250}👨‍👨‍👧‍👧
:::man-woman-boy-boy::{Sleep 250}👨‍👩‍👦‍👦
:::man-woman-girl::{Sleep 250}👨‍👩‍👧
:::man-woman-girl-boy::{Sleep 250}👨‍👩‍👧‍👦
:::man-woman-girl-girl::{Sleep 250}👨‍👩‍👧‍👧
:::male-doctor::{Sleep 250}👨‍⚕️
:::male-judge::{Sleep 250}👨‍⚖️
:::male-pilot::{Sleep 250}👨‍✈️
:::man-heart-man::{Sleep 250}👨‍❤️‍👨
:::man-kiss-man::{Sleep 250}👨‍❤️‍💋‍👨
:::woman-boy-boy::{Sleep 250}👩‍👦‍👦
:::woman-girl-boy::{Sleep 250}👩‍👧‍👦
:::woman-girl-girl::{Sleep 250}👩‍👧‍👧
:::woman-woman-boy::{Sleep 250}👩‍👩‍👦
:::woman-woman-boy-boy::{Sleep 250}👩‍👩‍👦‍👦
:::woman-woman-girl::{Sleep 250}👩‍👩‍👧
:::woman-woman-girl-boy::{Sleep 250}👩‍👩‍👧‍👦
:::woman-woman-girl-girl::{Sleep 250}👩‍👩‍👧‍👧
:::female-doctor::{Sleep 250}👩‍⚕️
:::female-judge::{Sleep 250}👩‍⚖️
:::female-pilot::{Sleep 250}👩‍✈️
:::woman-heart-man::{Sleep 250}👩‍❤️‍👨
:::woman-heart-woman::{Sleep 250}👩‍❤️‍👩
:::woman-kiss-man::{Sleep 250}👩‍❤️‍💋‍👨
:::woman-kiss-woman::{Sleep 250}👩‍❤️‍💋‍👩
:::female-police-officer::{Sleep 250}👮‍♀️
:::male-police-officer::{Sleep 250}👮‍♂️
:::woman-with-bunny-ears-partying::{Sleep 250}👯‍♀️
:::man-with-bunny-ears-partying::{Sleep 250}👯‍♂️
:::blond-haired-woman::{Sleep 250}👱‍♀️
:::blond-haired-man::{Sleep 250}👱‍♂️
:::woman-wearing-turban::{Sleep 250}👳‍♀️
:::man-wearing-turban::{Sleep 250}👳‍♂️
:::female-construction-worker::{Sleep 250}👷‍♀️
:::male-construction-worker::{Sleep 250}👷‍♂️
:::woman-tipping-hand::{Sleep 250}💁‍♀️
:::man-tipping-hand::{Sleep 250}💁‍♂️
:::female-guard::{Sleep 250}💂‍♀️
:::male-guard::{Sleep 250}💂‍♂️
:::woman-getting-massage::{Sleep 250}💆‍♀️
:::man-getting-massage::{Sleep 250}💆‍♂️
:::woman-getting-haircut::{Sleep 250}💇‍♀️
:::man-getting-haircut::{Sleep 250}💇‍♂️
:::female-detective::{Sleep 250}🕵️‍♀️
:::male-detective::{Sleep 250}🕵️‍♂️
:::woman-gesturing-no::{Sleep 250}🙅‍♀️
:::man-gesturing-no::{Sleep 250}🙅‍♂️
:::woman-gesturing-ok::{Sleep 250}🙆‍♀️
:::man-gesturing-ok::{Sleep 250}🙆‍♂️
:::woman-bowing::{Sleep 250}🙇‍♀️
:::man-bowing::{Sleep 250}🙇‍♂️
:::woman-raising-hand::{Sleep 250}🙋‍♀️
:::man-raising-hand::{Sleep 250}🙋‍♂️
:::woman-frowning::{Sleep 250}🙍‍♀️
:::man-frowning::{Sleep 250}🙍‍♂️
:::woman-pouting::{Sleep 250}🙎‍♀️
:::man-pouting::{Sleep 250}🙎‍♂️
:::woman-rowing-boat::{Sleep 250}🚣‍♀️
:::man-rowing-boat::{Sleep 250}🚣‍♂️
:::woman-biking::{Sleep 250}🚴‍♀️
:::man-biking::{Sleep 250}🚴‍♂️
:::woman-mountain-biking::{Sleep 250}🚵‍♀️
:::man-mountain-biking::{Sleep 250}🚵‍♂️
:::woman-walking::{Sleep 250}🚶‍♀️
:::man-walking::{Sleep 250}🚶‍♂️
:::woman-facepalming::{Sleep 250}🤦‍♀️
:::man-facepalming::{Sleep 250}🤦‍♂️
:::woman-shrugging::{Sleep 250}🤷‍♀️
:::man-shrugging::{Sleep 250}🤷‍♂️
:::woman-cartwheeling::{Sleep 250}🤸‍♀️
:::man-cartwheeling::{Sleep 250}🤸‍♂️
:::woman-juggling::{Sleep 250}🤹‍♀️
:::man-juggling::{Sleep 250}🤹‍♂️
:::woman-wrestling::{Sleep 250}🤼‍♀️
:::man-wrestling::{Sleep 250}🤼‍♂️
:::woman-playing-water-polo::{Sleep 250}🤽‍♀️
:::man-playing-water-polo::{Sleep 250}🤽‍♂️
:::woman-playing-handball::{Sleep 250}🤾‍♀️
:::man-playing-handball::{Sleep 250}🤾‍♂️
:::woman-bouncing-ball::{Sleep 250}⛹️‍♀️
:::man-bouncing-ball::{Sleep 250}⛹️‍♂️
:::fingers_crossed::{Sleep 250}🤞

:::woman_lifting_weights::{Sleep 250}🏋️‍♀️
:::man_lifting_weights::{Sleep 250}🏋️‍♂️

:::male_farmer::{Sleep 250}👨‍🌾
:::male_cook::{Sleep 250}👨‍🍳
:::male_student::{Sleep 250}👨‍🎓
:::male_singer::{Sleep 250}👨‍🎤
:::male_artist::{Sleep 250}👨‍🎨
:::male_teacher::{Sleep 250}👨‍🏫
:::male_factory_worker::{Sleep 250}👨‍🏭
:::man_boy::{Sleep 250}👨‍👦
:::man_girl::{Sleep 250}👨‍👧
:::male_technologist::{Sleep 250}👨‍💻
:::male_office_worker::{Sleep 250}👨‍💼
:::male_mechanic::{Sleep 250}👨‍🔧
:::male_scientist::{Sleep 250}👨‍🔬
:::male_astronaut::{Sleep 250}👨‍🚀
:::male_firefighter::{Sleep 250}👨‍🚒
:::female_farmer::{Sleep 250}👩‍🌾
:::female_cook::{Sleep 250}👩‍🍳
:::female_student::{Sleep 250}👩‍🎓
:::female_singer::{Sleep 250}👩‍🎤
:::female_artist::{Sleep 250}👩‍🎨
:::female_teacher::{Sleep 250}👩‍🏫
:::female_factory_worker::{Sleep 250}👩‍🏭
:::woman_boy::{Sleep 250}👩‍👦
:::woman_girl::{Sleep 250}👩‍👧
:::female_technologist::{Sleep 250}👩‍💻
:::female_office_worker::{Sleep 250}👩‍💼
:::female_mechanic::{Sleep 250}👩‍🔧
:::female_scientist::{Sleep 250}👩‍🔬
:::female_astronaut::{Sleep 250}👩‍🚀
:::female_firefighter::{Sleep 250}👩‍🚒
:::woman_surfing::{Sleep 250}🏄‍♀️
:::man_surfing::{Sleep 250}🏄‍♂️
:::woman_swimming::{Sleep 250}🏊‍♀️

:::woman_golfing::{Sleep 250}🏌️‍♀️
:::man_golfing::{Sleep 250}🏌️‍♂️
:::rainbow_flag::{Sleep 250}🏳️‍🌈
:::eye_in_speech_bubble::{Sleep 250}👁️‍🗨️
:::man_boy_boy::{Sleep 250}👨‍👦‍👦
:::man_girl_boy::{Sleep 250}👨‍👧‍👦
:::man_girl_girl::{Sleep 250}👨‍👧‍👧
:::man_man_boy::{Sleep 250}👨‍👨‍👦
:::man_man_boy_boy::{Sleep 250}👨‍👨‍👦‍👦
:::man_man_girl::{Sleep 250}👨‍👨‍👧
:::man_man_girl_boy::{Sleep 250}👨‍👨‍👧‍👦
:::man_man_girl_girl::{Sleep 250}👨‍👨‍👧‍👧
:::man_woman_boy::{Sleep 250}👨‍👩‍👦
:::man_woman_boy_boy::{Sleep 250}👨‍👩‍👦‍👦
:::man_woman_girl::{Sleep 250}👨‍👩‍👧
:::man_woman_girl_boy::{Sleep 250}👨‍👩‍👧‍👦
:::man_woman_girl_girl::{Sleep 250}👨‍👩‍👧‍👧
:::male_doctor::{Sleep 250}👨‍⚕️
:::male_judge::{Sleep 250}👨‍⚖️
:::male_pilot::{Sleep 250}👨‍✈️
:::man_heart_man::{Sleep 250}👨‍❤️‍👨
:::man_kiss_man::{Sleep 250}👨‍❤️‍💋‍👨
:::woman_boy_boy::{Sleep 250}👩‍👦‍👦
:::woman_girl_boy::{Sleep 250}👩‍👧‍👦
:::woman_girl_girl::{Sleep 250}👩‍👧‍👧
:::woman_woman_boy::{Sleep 250}👩‍👩‍👦
:::woman_woman_boy_boy::{Sleep 250}👩‍👩‍👦‍👦
:::woman_woman_girl::{Sleep 250}👩‍👩‍👧
:::woman_woman_girl_boy::{Sleep 250}👩‍👩‍👧‍👦
:::woman_woman_girl_girl::{Sleep 250}👩‍👩‍👧‍👧
:::female_doctor::{Sleep 250}👩‍⚕️
:::female_judge::{Sleep 250}👩‍⚖️
:::female_pilot::{Sleep 250}👩‍✈️
:::woman_heart_man::{Sleep 250}👩‍❤️‍👨
:::woman_heart_woman::{Sleep 250}👩‍❤️‍👩
:::woman_kiss_man::{Sleep 250}👩‍❤️‍💋‍👨
:::woman_kiss_woman::{Sleep 250}👩‍❤️‍💋‍👩
:::female_police_officer::{Sleep 250}👮‍♀️
:::male_police_officer::{Sleep 250}👮‍♂️
:::woman_with_bunny_ears_partying::{Sleep 250}👯‍♀️
:::man_with_bunny_ears_partying::{Sleep 250}👯‍♂️
:::blond_haired_woman::{Sleep 250}👱‍♀️
:::blond_haired_man::{Sleep 250}👱‍♂️
:::woman_wearing_turban::{Sleep 250}👳‍♀️
:::man_wearing_turban::{Sleep 250}👳‍♂️
:::female_construction_worker::{Sleep 250}👷‍♀️
:::male_construction_worker::{Sleep 250}👷‍♂️
:::woman_tipping_hand::{Sleep 250}💁‍♀️
:::man_tipping_hand::{Sleep 250}💁‍♂️
:::female_guard::{Sleep 250}💂‍♀️
:::male_guard::{Sleep 250}💂‍♂️
:::woman_getting_massage::{Sleep 250}💆‍♀️
:::man_getting_massage::{Sleep 250}💆‍♂️
:::woman_getting_haircut::{Sleep 250}💇‍♀️
:::man_getting_haircut::{Sleep 250}💇‍♂️
:::female_detective::{Sleep 250}🕵️‍♀️
:::male_detective::{Sleep 250}🕵️‍♂️
:::woman_gesturing_no::{Sleep 250}🙅‍♀️
:::man_gesturing_no::{Sleep 250}🙅‍♂️
:::woman_gesturing_ok::{Sleep 250}🙆‍♀️
:::man_gesturing_ok::{Sleep 250}🙆‍♂️
:::woman_bowing::{Sleep 250}🙇‍♀️
:::man_bowing::{Sleep 250}🙇‍♂️
:::woman_raising_hand::{Sleep 250}🙋‍♀️
:::man_raising_hand::{Sleep 250}🙋‍♂️
:::woman_frowning::{Sleep 250}🙍‍♀️
:::man_frowning::{Sleep 250}🙍‍♂️
:::woman_pouting::{Sleep 250}🙎‍♀️
:::man_pouting::{Sleep 250}🙎‍♂️
:::woman_rowing_boat::{Sleep 250}🚣‍♀️
:::man_rowing_boat::{Sleep 250}🚣‍♂️
:::woman_biking::{Sleep 250}🚴‍♀️
:::man_biking::{Sleep 250}🚴‍♂️
:::woman_mountain_biking::{Sleep 250}🚵‍♀️
:::man_mountain_biking::{Sleep 250}🚵‍♂️
:::woman_walking::{Sleep 250}🚶‍♀️
:::man_walking::{Sleep 250}🚶‍♂️
:::woman_facepalming::{Sleep 250}🤦‍♀️
:::man_facepalming::{Sleep 250}🤦‍♂️
:::woman_shrugging::{Sleep 250}🤷‍♀️
:::man_shrugging::{Sleep 250}🤷‍♂️
:::woman_cartwheeling::{Sleep 250}🤸‍♀️
:::man_cartwheeling::{Sleep 250}🤸‍♂️
:::woman_juggling::{Sleep 250}🤹‍♀️
:::man_juggling::{Sleep 250}🤹‍♂️
:::woman_wrestling::{Sleep 250}🤼‍♀️
:::man_wrestling::{Sleep 250}🤼‍♂️
:::woman_playing_water_polo::{Sleep 250}🤽‍♀️
:::man_playing_water_polo::{Sleep 250}🤽‍♂️
:::woman_playing_handball::{Sleep 250}🤾‍♀️
:::man_playing_handball::{Sleep 250}🤾‍♂️
:::woman_bouncing_ball::{Sleep 250}⛹️‍♀️
:::man_bouncing_ball::{Sleep 250}⛹️‍♂️
