; Nature
:::ocean::🌊
:::zap::⚡
:::wavy_dash::〰
:::volcano::🌋
:::seedling::🌱
:::evergreen_tree::🌲
:::deciduous_tree::🌳
:::palm_tree::🌴
:::cactus::🌵
:::white_flower::💮


; Time
:::watch::⌚
:::alarm_clock::⏰
:::stopwatch::⏱
:::timer_clock::⏲
:::hourglass::⌛
:::hourglass_flowing_sand::⏳


; Weather
:::droplet::💧
:::sunny::☀
:::cloud::☁
:::partly_sunny::⛅
:::thunder_cloud_and_rain::⛈
:::umbrella::☂
:::umbrella_with_rain_drops::☔
:::umbrella_on_ground::⛱
:::snowman::☃
:::snowman_without_snow::⛄
:::snowflake::❄
:::cyclone::🌀
:::foggy::🌁
:::closed_umbrella::🌂
:::night_with_stars::🌃
:::sunrise_over_mountains::🌄
:::sunrise::🌅
:::city_sunset::🌆
:::city_sunrise::🌇
:::rainbow::🌈


; Constallations
:::aries::♈
:::taurus::♉
:::gemini::♊
:::cancer::♋
:::leo::♌
:::virgo::♍
:::libra::♎
:::scorpius::♏
:::sagittarius::♐
:::capricorn::♑
:::aquarius::♒
:::pisces::♓


; Universe & Stars
:::telescope::🔭
:::comet::☄
:::star_and_crescent::☪
:::ophiuchus::⛎
:::star::⭐
:::eight_spoked_asterisk::✳
:::eight_pointed_black_star::✴
:::milky_way::🌌
:::earth_africa::🌍
:::earth_americas::🌎
:::earth_asia::🌏
:::globe_with_meridians::🌐
:::new_moon::🌑
:::waxing_crescent_moon::🌒
:::first_quarter_moon::🌓
:::moon::🌔
:::full_moon::🌕
:::waning_gibbous_moon::🌖
:::last_quarter_moon::🌗
:::waning_crescent_moon::🌘
:::crescent_moon::🌙
:::new_moon_with_face::🌚
:::first_quarter_moon_with_face::🌛
:::last_quarter_moon_with_face::🌜
:::full_moon_with_face::🌝
:::sun_with_face::🌞
:::star2::🌟
:::stars::🌠
:::waxing_gibbous_moon::🌔
:::sun_small_cloud::🌤
:::sun_behind_cloud::🌥
:::sun_behind_rain_cloud::🌦
:::lightning_cloud::🌩
:::tornado_cloud::🌪
:::waxing_gibbous_moon::🌔
:::sun_small_cloud::🌤
:::sun_behind_cloud::🌥
:::sun_behind_rain_cloud::🌦
:::lightning_cloud::🌩
:::tornado_cloud::🌪


; Animals
:::honeybee::🐝
:::flipper::🐬
:::paw_prints::🐾
:::rat::🐀
:::mouse2::🐁
:::ox::🐂
:::water_buffalo::🐃
:::cow2::🐄
:::tiger2::🐅
:::leopard::🐆
:::rabbit2::🐇
:::cat2::🐈
:::dragon::🐉
:::crocodile::🐊
:::whale2::🐋
:::snail::🐌
:::snake::🐍
:::racehorse::🐎
:::ram::🐏
:::goat::🐐
:::sheep::🐑
:::monkey::🐒
:::rooster::🐓
:::chicken::🐔
:::dog2::🐕
:::pig2::🐖
:::boar::🐗
:::elephant::🐘
:::octopus::🐙
:::shell::🐚
:::bug::🐛
:::ant::🐜
:::bee::🐝
:::beetle::🐞
:::fish::🐟
:::tropical_fish::🐠
:::blowfish::🐡
:::turtle::🐢
:::hatching_chick::🐣
:::baby_chick::🐤
:::hatched_chick::🐥
:::bird::🐦
:::penguin::🐧
:::koala::🐨
:::poodle::🐩
:::dromedary_camel::🐪
:::camel::🐫
:::dolphin::🐬
:::mouse::🐭
:::cow::🐮
:::tiger::🐯
:::rabbit::🐰
:::cat::🐱
:::dragon_face::🐲
:::whale::🐳
:::horse::🐴
:::monkey_face::🐵
:::dog::🐶
:::pig::🐷
:::frog::🐸
:::hamster::🐹
:::wolf::🐺
:::bear::🐻
:::panda_face::🐼
:::pig_nose::🐽
:::chipmunk::🐿
