; Office Materials
:::keyboard::⌨
:::headphones::🎧
:::envelope::✉
:::phone::☎
:::telephone::☎
:::telephone_receiver::📞
:::pager::📟
:::fax::📠
:::satellite_antenna::📡
:::100::💯
:::moneybag::💰
:::currency_exchange::💱
:::heavy_dollar_sign::💲
:::credit_card::💳
:::yen::💴
:::dollar::💵
:::euro::💶
:::pound::💷
:::money_with_wings::💸
:::chart::💹
:::seat::💺
:::computer::💻
:::briefcase::💼
:::minidisc::💽
:::floppy_disk::💾
:::cd::💿
:::dvd::📀
:::file_folder::📁
:::open_file_folder::📂
:::page_with_curl::📃
:::page_facing_up::📄
:::date::📅
:::calendar::📆
:::card_index::📇
:::chart_with_upwards_trend::📈
:::chart_with_downwards_trend::📉
:::bar_chart::📊
:::clipboard::📋
:::pushpin::📌
:::round_pushpin::📍
:::paperclip::📎
:::straight_ruler::📏
:::triangular_ruler::📐
:::bookmark_tabs::📑
:::ledger::📒
:::notebook::📓
:::notebook_with_decorative_cover::📔
:::closed_book::📕
:::book::📖
:::green_book::📗
:::blue_book::📘
:::orange_book::📙
:::books::📚
:::name_badge::📛
:::scroll::📜
:::memo::📝
:::loudspeaker::📢
:::mega::📣
:::outbox_tray::📤
:::inbox_tray::📥
:::package::📦
:::e_mail::📧
:::incoming_envelope::📨
:::envelope_with_arrow::📩
:::mailbox_closed::📪
:::mailbox::📫
:::mailbox_with_mail::📬
:::mailbox_with_no_mail::📭
:::postbox::📮
:::postal_horn::📯
:::newspaper::📰
:::iphone::📱
:::calling::📲
:::vibration_mode::📳
:::mobile_phone_off::📴
:::no_mobile_phones::📵
:::signal_strength::📶
:::camera::📷
:::camera_with_flash::📸
:::video_camera::📹
:::microscope::🔬
:::tv::📺
:::radio::📻
:::vhs::📼
:::film_projector::📽
:::battery::🔋
:::electric_plug::🔌
:::lock_with_ink_pen::🔏
:::closed_lock_with_key::🔐
:::key::🔑
:::lock::🔒
:::unlock::🔓
:::bell::🔔
:::no_bell::🔕


; Developer
:::speech_balloon::💬
:::thought_balloon::💭
:::mag::🔍 ; Search
:::mag_right::🔎
:::checkbox::☑
:::white_circle::⚪
:::black_circle::⚫
:::bookmark::🔖
:::radio_button::🔘
:::check::✅
:::warning::⚠
:::no_entry::⛔
:::scissors::✂
:::white_check_mark::✅
:::email::✉
:::e-mail::📧
:::pencil2::✏
:::black_nib::✒
:::heavy_check_mark::✔
:::heavy_multiplication_x::✖
:::x::❌
:::negative_squared_cross_mark::❎
:::question::❓
:::grey_question::❔
:::grey_exclamation::❕
:::exclamation::❗
:::heavy_heart_exclamation_mark_ornament::❣
:::heavy_plus_sign::➕
:::heavy_minus_sign::➖
:::heavy_division_sign::➗
:::o::⭕
:::heavy_exclamation_mark::❗
:::triangular_flag_on_post::🚩
:::no_entry_sign::🚫
:::open_book::📖
:::pencil::📝
:::link::🔗
:::telephone::☎
:::sailboat::⛵
:::envelope::✉
:::raised_hand::✋
:::heavy_exclamation_mark::❗
:::capital_abcd::🔠
:::abcd::🔡
:::1234::🔢
:::symbols::🔣
:::abc::🔤
:::black_square_button::🔲
:::white_square_button::🔳
:::red_circle::🔴
:::large_blue_circle::🔵
:::large_orange_diamond::🔶
:::large_blue_diamond::🔷
:::small_orange_diamond::🔸
:::small_blue_diamond::🔹
:::small_red_triangle::🔺
:::small_red_triangle_down::🔻


; Radio
:::eject::⏏
:::play_pause::⏯
:::fast_forward::⏭
:::rewind::⏮
:::arrow_double_up::⏫
:::arrow_double_down::⏬
:::black_right_pointing_double_triangle_wi::⏭
:::black_left_pointing_double_triangle_wit::⏮
:::black_right_pointing_triangle_with_doub::⏯
:::arrow_forward::▶
:::arrow_backward::◀
:::twisted_rightwards_arrows::🔀
:::repeat::🔁
:::repeat_one::🔂
:::arrows_clockwise::🔃
:::arrows_counterclockwise::🔄
:::low_brightness::🔅
:::high_brightness::🔆
:::mute::🔇
:::speaker::🔈
:::sound::🔉
:::loud_sound::🔊



; Clocks
:::clock1::🕐
:::clock2::🕑
:::clock3::🕒
:::clock4::🕓
:::clock5::🕔
:::clock6::🕕
:::clock7::🕖
:::clock8::🕗
:::clock9::🕘
:::clock10::🕙
:::clock11::🕚
:::clock12::🕛
:::clock130::🕜
:::clock230::🕝
:::clock330::🕞
:::clock430::🕟
:::clock530::🕠
:::clock630::🕡
:::clock730::🕢
:::clock830::🕣
:::clock930::🕤
:::clock1030::🕥
:::clock1130::🕦
:::clock1230::🕧

; Boxes
:::black_small_square::▪
:::white_small_square::▫
:::white_medium_square::◻
:::black_medium_square::◼
:::white_medium_small_square::◽
:::black_medium_small_square::◾
:::black_large_square::⬛
:::white_large_square::⬜
