; Hand Gestures
:::fist::✊
:::hand::✋
:::v::✌
:::writing_hand::✍
:::raised_hand::✋
:::point_up::☝
:::point_up_2::👆
:::point_down::👇
:::point_left::👈
:::point_right::👉
:::facepunch::👊
:::wave::👋
:::ok_hand::👌
:::+1::👍
:::_1::👎
:::clap::👏
:::open_hands::👐
:::punch::👊
:::thumbsup::👍
:::-1::👎
:::thumbsdown::👎


:::tongue_face::😛
:::white_frowning_face::☹
:::relaxed::☺

:::satisfied::😆
:::grinning::😀
:::grin::😁
:::joy::😂
:::smiley::😃
:::smile::😄
:::sweat_smile::😅
:::laughing::😆
:::innocent::😇
:::smiling_imp::😈
:::wink::😉
:::blush::😊
:::yum::😋
:::relieved::😌
:::heart_eyes::😍
:::sunglasses::😎
:::smirk::😏
:::neutral_face::😐
:::expressionless::😑
:::unamused::😒
:::sweat::😓
:::pensive::😔
:::confused::😕
:::confounded::😖
:::kissing::😗
:::kissing_heart::😘
:::kissing_smiling_eyes::😙
:::kissing_closed_eyes::😚
:::stuck_out_tongue::😛
:::stuck_out_tongue_winking_eye::😜
:::stuck_out_tongue_closed_eyes::😝
:::disappointed::😞
:::worried::😟
:::angry::😠
:::rage::😡
:::cry::😢
:::persevere::😣
:::triumph::😤
:::disappointed_relieved::😥
:::frowning::😦
:::anguished::😧
:::fearful::😨
:::weary::😩
:::sleepy::😪
:::tired_face::😫
:::grimacing::😬
:::sob::😭
:::open_mouth::😮
:::hushed::😯
:::cold_sweat::😰
:::scream::😱
:::astonished::😲
:::flushed::😳
:::sleeping::😴
:::dizzy_face::😵
:::no_mouth::😶
:::mask::😷
:::smile_cat::😸
:::joy_cat::😹
:::smiley_cat::😺
:::heart_eyes_cat::😻
:::smirk_cat::😼
:::kissing_cat::😽
:::pouting_cat::😾
:::crying_cat_face::😿
:::scream_cat::🙀
:::slightly_frowning_face::🙁
:::slightly_smiling_face::🙂
:::upside_down_face::🙃
:::face_with_rolling_eyes::🙄
:::no_good::🙅
:::ok_woman::🙆
:::bow::🙇

:::raising_hand::🙋
:::raised_hands::🙌
:::person_frowning::🙍
:::person_with_pouting_face::🙎
:::pray::🙏


:::male-farmer::👨‍🌾
:::male-cook::👨‍🍳
:::male-student::👨‍🎓
:::male-singer::👨‍🎤
:::male-artist::👨‍🎨
:::male-teacher::👨‍🏫
:::male-factory-worker::👨‍🏭
:::man-boy::👨‍👦
:::man-girl::👨‍👧
:::male-technologist::👨‍💻
:::male-office-worker::👨‍💼
:::male-mechanic::👨‍🔧
:::male-scientist::👨‍🔬
:::male-astronaut::👨‍🚀
:::male-firefighter::👨‍🚒
:::female-farmer::👩‍🌾
:::female-cook::👩‍🍳
:::female-student::👩‍🎓
:::female-singer::👩‍🎤
:::female-artist::👩‍🎨
:::female-teacher::👩‍🏫
:::female-factory-worker::👩‍🏭
:::woman-boy::👩‍👦
:::woman-girl::👩‍👧
:::female-technologist::👩‍💻
:::female-office-worker::👩‍💼
:::female-mechanic::👩‍🔧
:::female-scientist::👩‍🔬
:::female-astronaut::👩‍🚀
:::female-firefighter::👩‍🚒
:::woman-running::🏃‍♀️
:::man-running::🏃‍♂️
:::woman-surfing::🏄‍♀️
:::man-surfing::🏄‍♂️
:::woman-swimming::🏊‍♀️
:::man-swimming::🏊‍♂️
:::woman-lifting-weights::🏋️‍♀️
:::man-lifting-weights::🏋️‍♂️
:::woman-golfing::🏌️‍♀️
:::man-golfing::🏌️‍♂️
:::rainbow-flag::🏳️‍🌈
:::eye-in-speech-bubble::👁️‍🗨️
:::man-boy-boy::👨‍👦‍👦
:::man-girl-boy::👨‍👧‍👦
:::man-girl-girl::👨‍👧‍👧
:::man-man-boy::👨‍👨‍👦
:::man-man-boy-boy::👨‍👨‍👦‍👦
:::man-man-girl::👨‍👨‍👧
:::man-man-girl-boy::👨‍👨‍👧‍👦
:::man-man-girl-girl::👨‍👨‍👧‍👧
:::man-woman-boy-boy::👨‍👩‍👦‍👦
:::man-woman-girl::👨‍👩‍👧
:::man-woman-girl-boy::👨‍👩‍👧‍👦
:::man-woman-girl-girl::👨‍👩‍👧‍👧
:::male-doctor::👨‍⚕️
:::male-judge::👨‍⚖️
:::male-pilot::👨‍✈️
:::man-heart-man::👨‍❤️‍👨
:::man-kiss-man::👨‍❤️‍💋‍👨
:::woman-boy-boy::👩‍👦‍👦
:::woman-girl-boy::👩‍👧‍👦
:::woman-girl-girl::👩‍👧‍👧
:::woman-woman-boy::👩‍👩‍👦
:::woman-woman-boy-boy::👩‍👩‍👦‍👦
:::woman-woman-girl::👩‍👩‍👧
:::woman-woman-girl-boy::👩‍👩‍👧‍👦
:::woman-woman-girl-girl::👩‍👩‍👧‍👧
:::female-doctor::👩‍⚕️
:::female-judge::👩‍⚖️
:::female-pilot::👩‍✈️
:::woman-heart-man::👩‍❤️‍👨
:::woman-heart-woman::👩‍❤️‍👩
:::woman-kiss-man::👩‍❤️‍💋‍👨
:::woman-kiss-woman::👩‍❤️‍💋‍👩
:::female-police-officer::👮‍♀️
:::male-police-officer::👮‍♂️
:::woman-with-bunny-ears-partying::👯‍♀️
:::man-with-bunny-ears-partying::👯‍♂️
:::blond-haired-woman::👱‍♀️
:::blond-haired-man::👱‍♂️
:::woman-wearing-turban::👳‍♀️
:::man-wearing-turban::👳‍♂️
:::female-construction-worker::👷‍♀️
:::male-construction-worker::👷‍♂️
:::woman-tipping-hand::💁‍♀️
:::man-tipping-hand::💁‍♂️
:::female-guard::💂‍♀️
:::male-guard::💂‍♂️
:::woman-getting-massage::💆‍♀️
:::man-getting-massage::💆‍♂️
:::woman-getting-haircut::💇‍♀️
:::man-getting-haircut::💇‍♂️
:::female-detective::🕵️‍♀️
:::male-detective::🕵️‍♂️
:::woman-gesturing-no::🙅‍♀️
:::man-gesturing-no::🙅‍♂️
:::woman-gesturing-ok::🙆‍♀️
:::man-gesturing-ok::🙆‍♂️
:::woman-bowing::🙇‍♀️
:::man-bowing::🙇‍♂️
:::woman-raising-hand::🙋‍♀️
:::man-raising-hand::🙋‍♂️
:::woman-frowning::🙍‍♀️
:::man-frowning::🙍‍♂️
:::woman-pouting::🙎‍♀️
:::man-pouting::🙎‍♂️
:::woman-rowing-boat::🚣‍♀️
:::man-rowing-boat::🚣‍♂️
:::woman-biking::🚴‍♀️
:::man-biking::🚴‍♂️
:::woman-mountain-biking::🚵‍♀️
:::man-mountain-biking::🚵‍♂️
:::woman-walking::🚶‍♀️
:::man-walking::🚶‍♂️
:::woman-facepalming::🤦‍♀️
:::man-facepalming::🤦‍♂️
:::woman-shrugging::🤷‍♀️
:::man-shrugging::🤷‍♂️
:::woman-cartwheeling::🤸‍♀️
:::man-cartwheeling::🤸‍♂️
:::woman-juggling::🤹‍♀️
:::man-juggling::🤹‍♂️
:::woman-wrestling::🤼‍♀️
:::man-wrestling::🤼‍♂️
:::woman-playing-water-polo::🤽‍♀️
:::man-playing-water-polo::🤽‍♂️
:::woman-playing-handball::🤾‍♀️
:::man-playing-handball::🤾‍♂️
:::woman-bouncing-ball::⛹️‍♀️
:::man-bouncing-ball::⛹️‍♂️
:::fingers_crossed::🤞

:::woman_lifting_weights::🏋️‍♀️
:::man_lifting_weights::🏋️‍♂️

:::male_farmer::👨‍🌾
:::male_cook::👨‍🍳
:::male_student::👨‍🎓
:::male_singer::👨‍🎤
:::male_artist::👨‍🎨
:::male_teacher::👨‍🏫
:::male_factory_worker::👨‍🏭
:::man_boy::👨‍👦
:::man_girl::👨‍👧
:::male_technologist::👨‍💻
:::male_office_worker::👨‍💼
:::male_mechanic::👨‍🔧
:::male_scientist::👨‍🔬
:::male_astronaut::👨‍🚀
:::male_firefighter::👨‍🚒
:::female_farmer::👩‍🌾
:::female_cook::👩‍🍳
:::female_student::👩‍🎓
:::female_singer::👩‍🎤
:::female_artist::👩‍🎨
:::female_teacher::👩‍🏫
:::female_factory_worker::👩‍🏭
:::woman_boy::👩‍👦
:::woman_girl::👩‍👧
:::female_technologist::👩‍💻
:::female_office_worker::👩‍💼
:::female_mechanic::👩‍🔧
:::female_scientist::👩‍🔬
:::female_astronaut::👩‍🚀
:::female_firefighter::👩‍🚒
:::woman_surfing::🏄‍♀️
:::man_surfing::🏄‍♂️
:::woman_swimming::🏊‍♀️

:::woman_golfing::🏌️‍♀️
:::man_golfing::🏌️‍♂️
:::rainbow_flag::🏳️‍🌈
:::eye_in_speech_bubble::👁️‍🗨️
:::man_boy_boy::👨‍👦‍👦
:::man_girl_boy::👨‍👧‍👦
:::man_girl_girl::👨‍👧‍👧
:::man_man_boy::👨‍👨‍👦
:::man_man_boy_boy::👨‍👨‍👦‍👦
:::man_man_girl::👨‍👨‍👧
:::man_man_girl_boy::👨‍👨‍👧‍👦
:::man_man_girl_girl::👨‍👨‍👧‍👧
:::man_woman_boy::👨‍👩‍👦
:::man_woman_boy_boy::👨‍👩‍👦‍👦
:::man_woman_girl::👨‍👩‍👧
:::man_woman_girl_boy::👨‍👩‍👧‍👦
:::man_woman_girl_girl::👨‍👩‍👧‍👧
:::male_doctor::👨‍⚕️
:::male_judge::👨‍⚖️
:::male_pilot::👨‍✈️
:::man_heart_man::👨‍❤️‍👨
:::man_kiss_man::👨‍❤️‍💋‍👨
:::woman_boy_boy::👩‍👦‍👦
:::woman_girl_boy::👩‍👧‍👦
:::woman_girl_girl::👩‍👧‍👧
:::woman_woman_boy::👩‍👩‍👦
:::woman_woman_boy_boy::👩‍👩‍👦‍👦
:::woman_woman_girl::👩‍👩‍👧
:::woman_woman_girl_boy::👩‍👩‍👧‍👦
:::woman_woman_girl_girl::👩‍👩‍👧‍👧
:::female_doctor::👩‍⚕️
:::female_judge::👩‍⚖️
:::female_pilot::👩‍✈️
:::woman_heart_man::👩‍❤️‍👨
:::woman_heart_woman::👩‍❤️‍👩
:::woman_kiss_man::👩‍❤️‍💋‍👨
:::woman_kiss_woman::👩‍❤️‍💋‍👩
:::female_police_officer::👮‍♀️
:::male_police_officer::👮‍♂️
:::woman_with_bunny_ears_partying::👯‍♀️
:::man_with_bunny_ears_partying::👯‍♂️
:::blond_haired_woman::👱‍♀️
:::blond_haired_man::👱‍♂️
:::woman_wearing_turban::👳‍♀️
:::man_wearing_turban::👳‍♂️
:::female_construction_worker::👷‍♀️
:::male_construction_worker::👷‍♂️
:::woman_tipping_hand::💁‍♀️
:::man_tipping_hand::💁‍♂️
:::female_guard::💂‍♀️
:::male_guard::💂‍♂️
:::woman_getting_massage::💆‍♀️
:::man_getting_massage::💆‍♂️
:::woman_getting_haircut::💇‍♀️
:::man_getting_haircut::💇‍♂️
:::female_detective::🕵️‍♀️
:::male_detective::🕵️‍♂️
:::woman_gesturing_no::🙅‍♀️
:::man_gesturing_no::🙅‍♂️
:::woman_gesturing_ok::🙆‍♀️
:::man_gesturing_ok::🙆‍♂️
:::woman_bowing::🙇‍♀️
:::man_bowing::🙇‍♂️
:::woman_raising_hand::🙋‍♀️
:::man_raising_hand::🙋‍♂️
:::woman_frowning::🙍‍♀️
:::man_frowning::🙍‍♂️
:::woman_pouting::🙎‍♀️
:::man_pouting::🙎‍♂️
:::woman_rowing_boat::🚣‍♀️
:::man_rowing_boat::🚣‍♂️
:::woman_biking::🚴‍♀️
:::man_biking::🚴‍♂️
:::woman_mountain_biking::🚵‍♀️
:::man_mountain_biking::🚵‍♂️
:::woman_walking::🚶‍♀️
:::man_walking::🚶‍♂️
:::woman_facepalming::🤦‍♀️
:::man_facepalming::🤦‍♂️
:::woman_shrugging::🤷‍♀️
:::man_shrugging::🤷‍♂️
:::woman_cartwheeling::🤸‍♀️
:::man_cartwheeling::🤸‍♂️
:::woman_juggling::🤹‍♀️
:::man_juggling::🤹‍♂️
:::woman_wrestling::🤼‍♀️
:::man_wrestling::🤼‍♂️
:::woman_playing_water_polo::🤽‍♀️
:::man_playing_water_polo::🤽‍♂️
:::woman_playing_handball::🤾‍♀️
:::man_playing_handball::🤾‍♂️
:::woman_bouncing_ball::⛹️‍♀️
:::man_bouncing_ball::⛹️‍♂️
