:::cl::🆑
:::cool::🆒
:::free::🆓
:::id::🆔
:::new::🆕
:::ng::🆖
:::ok::🆗
:::sos::🆘
:::up::🆙
:::vs::🆚

:::hash::#⃣
:::keycap_star::*⃣
:::zero::0⃣
:::one::1⃣
:::two::2⃣
:::three::3⃣
:::four::4⃣
:::five::5⃣
:::six::6⃣
:::seven::7⃣
:::eight::8⃣
:::nine::9⃣
:::keycap_ten::🔟

:::flag-ac::🇦🇨
:::flag-ad::🇦🇩
:::flag-ae::🇦🇪
:::flag-af::🇦🇫
:::flag-ag::🇦🇬
:::flag-ai::🇦🇮
:::flag-al::🇦🇱
:::flag-am::🇦🇲
:::flag-ao::🇦🇴
:::flag-aq::🇦🇶
:::flag-ar::🇦🇷
:::flag-as::🇦🇸
:::flag-at::🇦🇹
:::flag-au::🇦🇺
:::flag-aw::🇦🇼
:::flag-ax::🇦🇽
:::flag-az::🇦🇿
:::flag-ba::🇧🇦
:::flag-bb::🇧🇧
:::flag-bd::🇧🇩
:::flag-be::🇧🇪
:::flag-bf::🇧🇫
:::flag-bg::🇧🇬
:::flag-bh::🇧🇭
:::flag-bi::🇧🇮
:::flag-bj::🇧🇯
:::flag-bl::🇧🇱
:::flag-bm::🇧🇲
:::flag-bn::🇧🇳
:::flag-bo::🇧🇴
:::flag-bq::🇧🇶
:::flag-br::🇧🇷
:::flag-bs::🇧🇸
:::flag-bt::🇧🇹
:::flag-bv::🇧🇻
:::flag-bw::🇧🇼
:::flag-by::🇧🇾
:::flag-bz::🇧🇿
:::flag-ca::🇨🇦
:::flag-cc::🇨🇨
:::flag-cd::🇨🇩
:::flag-cf::🇨🇫
:::flag-cg::🇨🇬
:::flag-ch::🇨🇭
:::flag-ci::🇨🇮
:::flag-ck::🇨🇰
:::flag-cl::🇨🇱
:::flag-cm::🇨🇲
:::flag-cn::🇨🇳
:::cn::🇨🇳
:::flag-co::🇨🇴
:::flag-cp::🇨🇵
:::flag-cr::🇨🇷
:::flag-cu::🇨🇺
:::flag-cv::🇨🇻
:::flag-cw::🇨🇼
:::flag-cx::🇨🇽
:::flag-cy::🇨🇾
:::flag-cz::🇨🇿
:::flag-de::🇩🇪
:::de::🇩🇪
:::flag-dg::🇩🇬
:::flag-dj::🇩🇯
:::flag-dk::🇩🇰
:::flag-dm::🇩🇲
:::flag-do::🇩🇴
:::flag-dz::🇩🇿
:::flag-ea::🇪🇦
:::flag-ec::🇪🇨
:::flag-ee::🇪🇪
:::flag-eg::🇪🇬
:::flag-eh::🇪🇭
:::flag-er::🇪🇷
:::flag-es::🇪🇸
:::es::🇪🇸
:::flag-et::🇪🇹
:::flag-eu::🇪🇺
:::flag-fi::🇫🇮
:::flag-fj::🇫🇯
:::flag-fk::🇫🇰
:::flag-fm::🇫🇲
:::flag-fo::🇫🇴
:::flag-fr::🇫🇷
:::fr::🇫🇷
:::flag-ga::🇬🇦
:::flag-gb::🇬🇧
:::gb::🇬🇧
:::uk::🇬🇧
:::flag-gd::🇬🇩
:::flag-ge::🇬🇪
:::flag-gf::🇬🇫
:::flag-gg::🇬🇬
:::flag-gh::🇬🇭
:::flag-gi::🇬🇮
:::flag-gl::🇬🇱
:::flag-gm::🇬🇲
:::flag-gn::🇬🇳
:::flag-gp::🇬🇵
:::flag-gq::🇬🇶
:::flag-gr::🇬🇷
:::flag-gs::🇬🇸
:::flag-gt::🇬🇹
:::flag-gu::🇬🇺
:::flag-gw::🇬🇼
:::flag-gy::🇬🇾
:::flag-hk::🇭🇰
:::flag-hm::🇭🇲
:::flag-hn::🇭🇳
:::flag-hr::🇭🇷
:::flag-ht::🇭🇹
:::flag-hu::🇭🇺
:::flag-ic::🇮🇨
:::flag-id::🇮🇩
:::flag-ie::🇮🇪
:::flag-il::🇮🇱
:::flag-im::🇮🇲
:::flag-in::🇮🇳
:::flag-io::🇮🇴
:::flag-iq::🇮🇶
:::flag-ir::🇮🇷
:::flag-is::🇮🇸
:::flag-it::🇮🇹
:::it::🇮🇹
:::flag-je::🇯🇪
:::flag-jm::🇯🇲
:::flag-jo::🇯🇴
:::flag-jp::🇯🇵
:::jp::🇯🇵
:::flag-ke::🇰🇪
:::flag-kg::🇰🇬
:::flag-kh::🇰🇭
:::flag-ki::🇰🇮
:::flag-km::🇰🇲
:::flag-kn::🇰🇳
:::flag-kp::🇰🇵
:::flag-kr::🇰🇷
:::kr::🇰🇷
:::flag-kw::🇰🇼
:::flag-ky::🇰🇾
:::flag-kz::🇰🇿
:::flag-la::🇱🇦
:::flag-lb::🇱🇧
:::flag-lc::🇱🇨
:::flag-li::🇱🇮
:::flag-lk::🇱🇰
:::flag-lr::🇱🇷
:::flag-ls::🇱🇸
:::flag-lt::🇱🇹
:::flag-lu::🇱🇺
:::flag-lv::🇱🇻
:::flag-ly::🇱🇾
:::flag-ma::🇲🇦
:::flag-mc::🇲🇨
:::flag-md::🇲🇩
:::flag-me::🇲🇪
:::flag-mf::🇲🇫
:::flag-mg::🇲🇬
:::flag-mh::🇲🇭
:::flag-mk::🇲🇰
:::flag-ml::🇲🇱
:::flag-mm::🇲🇲
:::flag-mn::🇲🇳
:::flag-mo::🇲🇴
:::flag-mp::🇲🇵
:::flag-mq::🇲🇶
:::flag-mr::🇲🇷
:::flag-ms::🇲🇸
:::flag-mt::🇲🇹
:::flag-mu::🇲🇺
:::flag-mv::🇲🇻
:::flag-mw::🇲🇼
:::flag-mx::🇲🇽
:::flag-my::🇲🇾
:::flag-mz::🇲🇿
:::flag-na::🇳🇦
:::flag-nc::🇳🇨
:::flag-ne::🇳🇪
:::flag-nf::🇳🇫
:::flag-ng::🇳🇬
:::flag-ni::🇳🇮
:::flag-nl::🇳🇱
:::flag-no::🇳🇴
:::flag-np::🇳🇵
:::flag-nr::🇳🇷
:::flag-nu::🇳🇺
:::flag-nz::🇳🇿
:::flag-om::🇴🇲
:::flag-pa::🇵🇦
:::flag-pe::🇵🇪
:::flag-pf::🇵🇫
:::flag-pg::🇵🇬
:::flag-ph::🇵🇭
:::flag-pk::🇵🇰
:::flag-pl::🇵🇱
:::flag-pm::🇵🇲
:::flag-pn::🇵🇳
:::flag-pr::🇵🇷
:::flag-ps::🇵🇸
:::flag-pt::🇵🇹
:::flag-pw::🇵🇼
:::flag-py::🇵🇾
:::flag-qa::🇶🇦
:::flag-re::🇷🇪
:::flag-ro::🇷🇴
:::flag-rs::🇷🇸
:::flag-ru::🇷🇺
:::ru::🇷🇺
:::flag-rw::🇷🇼
:::flag-sa::🇸🇦
:::flag-sb::🇸🇧
:::flag-sc::🇸🇨
:::flag-sd::🇸🇩
:::flag-se::🇸🇪
:::flag-sg::🇸🇬
:::flag-sh::🇸🇭
:::flag-si::🇸🇮
:::flag-sj::🇸🇯
:::flag-sk::🇸🇰
:::flag-sl::🇸🇱
:::flag-sm::🇸🇲
:::flag-sn::🇸🇳
:::flag-so::🇸🇴
:::flag-sr::🇸🇷
:::flag-ss::🇸🇸
:::flag-st::🇸🇹
:::flag-sv::🇸🇻
:::flag-sx::🇸🇽
:::flag-sy::🇸🇾
:::flag-sz::🇸🇿
:::flag-ta::🇹🇦
:::flag-tc::🇹🇨
:::flag-td::🇹🇩
:::flag-tf::🇹🇫
:::flag-tg::🇹🇬
:::flag-th::🇹🇭
:::flag-tj::🇹🇯
:::flag-tk::🇹🇰
:::flag-tl::🇹🇱
:::flag-tm::🇹🇲
:::flag-tn::🇹🇳
:::flag-to::🇹🇴
:::flag-tr::🇹🇷
:::flag-tt::🇹🇹
:::flag-tv::🇹🇻
:::flag-tw::🇹🇼
:::flag-tz::🇹🇿
:::flag-ua::🇺🇦
:::flag-ug::🇺🇬
:::flag-um::🇺🇲
:::flag-un::🇺🇳
:::flag-us::🇺🇸
:::us::🇺🇸
:::flag-uy::🇺🇾
:::flag-uz::🇺🇿
:::flag-va::🇻🇦
:::flag-vc::🇻🇨
:::flag-ve::🇻🇪
:::flag-vg::🇻🇬
:::flag-vi::🇻🇮
:::flag-vn::🇻🇳
:::flag-vu::🇻🇺
:::flag-wf::🇼🇫
:::flag-ws::🇼🇸
:::flag-xk::🇽🇰
:::flag-ye::🇾🇪
:::flag-yt::🇾🇹
:::flag-za::🇿🇦
:::flag-zm::🇿🇲
:::flag-zw::🇿🇼